### ISSUE TITLE
All initialTBoxAnnotations.nt throw error

### ISSUE THREAD

**Issue by fmdelvalle** [vivo-project/VIVO#3615] opened 2022-01-19 15:37 UTC
**Describe the bug**
All the initialTBoxAnnotations_<language>.nt from the VIVO-languages tbox/firsttime directory make VIVO throw an Exception on start.

**To Reproduce**
Compile VIVO with at least one of these files. You can copy from VIVO-languages to installer with:

cp -rf VIVO-languages/es/home/src/main/resources/rdf/i18n/es/* VIVO/installer/home/src/main/resources/rdf/

Note: maybe you don't need to copy any files, it is just a workaround because VIVO 1.12.1/2 is not installable right now.

Start VIVO with mvn install -s settings.xml [-Dvivo-installer-dir=...]

In the log file you will see something like this (once per language):

2022-01-19 16:05:41,644 ERROR [UpdateKnowledgeBase] Unable to load RDF from initialTBoxAnnotations_es.nt
org.apache.jena.riot.RiotException: [line: 1, col: 7 ] Element or attribute do not match QName production: QName::=(NCName':')?NCName. 
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:153)
        at org.apache.jena.riot.lang.ReaderRIOTRDFXML$ErrorHandlerBridge.fatalError(ReaderRIOTRDFXML.java:313)
        at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLEntityScanner.scanQName(Unknown Source)
...

**Expected behavior**
It should not throw. It seems to be trying to load the .nt files as .xml. If I rename these files to .n3, it works flawlessly. It is also not an encoding issue, as it happens even with en_US ASCII files.

**Environment (please complete the following information):**
 - OS: Windows
 - Tomcat version 8
 - VIVO version 1.12.2-SNAPSHOT
 - Apache Solr 8.11

**Additional context**
Jena loader does not seem to recognize .nt files properly, but it loads .n3 and possibly .rdf just fine.

**Comment by chenejac** [comment] 2022-01-20 08:11
@fmdelvalle thanks for reporting this. I can't reproduce this issue at the moment, and it might be because my workaround of missing languages problem is not the same as yours. Therefore, I suggest to wait resolving missing languages issue at 1.12.X (probably by merging this PR - https://github.com/vivo-project/VIVO/pull/3611) , and to test it again.

**Closed** 2022-09-14 11:21 UTC
